[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
agent_registry_8004 = "GkC3LyywEPy3LaMr2XUHHKb7XMdd9T2aZ8iohtNGPXJg"

[programs.devnet]
agent_registry_8004 = "GkC3LyywEPy3LaMr2XUHHKb7XMdd9T2aZ8iohtNGPXJg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/core-minimal.ts"

# Clone Metaplex Core program for local testing
[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
